services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./signoz/collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - ${OTEL_FORWARD_PORT:-4318}:4318
    restart: always
