receivers:
  otlp:
    protocols:
      http:

processors:
  batch:

exporters:
  otlphttp:
    endpoint: "http://signoz:4318"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
